[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "upconversion_models"
version = "0.1.0"
dependencies = [
    "jablonski @ git+https://github.com/dyscolab/jablonski.git@8647489", 
    "poincare @ git+https://github.com/dyscolab/poincare.git@0b4b47d"
]

[tool.setuptools.packages.find]
where = ["src"]
